[build]
command = "pnpm build"
publish = "dist/public"

[[headers]]
for = "/show/*/*.mp3"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/sw.js"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/show/*/*.svg"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/show/*/*.json"
  [headers.values]
  Cache-Control = "public, max-age=86400"

[[headers]]
for = "/show/*/captions/*.vtt"
  [headers.values]
  Cache-Control = "public, max-age=86400"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
